#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    IR_SHORT,      sensorReflection)
#pragma config(Sensor, in2,    IR_LONG,      sensorReflection)
#pragma config(Sensor, dgtl1,  RedLED,         sensorDigitalOut)
#pragma config(Sensor, dgtl3,  button1,        sensorTouch)
#pragma config(Sensor, dgtl4,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          motor3,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


const   int OFF = 0;
const   int ON  = 1;


task main ()
{
    SensorValue(RedLED)= OFF;

    while( true ) {


        if (SensorValue(sonarSensor) <= 35) {
            // Close to wall
        		motor[motor1] = 0;
        		motor[motor2] = 0;
        		SensorValue(RedLED) = ON;
        } else {
           // Safe distance from wall
        		SensorValue(RedLED) = OFF;
        		motor[motor1] = -30;
        		motor[motor2] = -24;
        }
    }  // while(true)
}//main
